# Generated by Django 5.0.6 on 2024-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
