# Generated by Django 5.0.6 on 2024-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0002_alter_posts_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
