# Generated by Django 5.0.6 on 2024-05-21 11:21

from django.db import migrations, models

import posts_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0003_posts_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="cover_path",
            field=models.ImageField(
                null=True, upload_to=posts_app.models.upload_cover
            ),
        ),
    ]
