# Generated by Django 5.0.6 on 2024-05-21 11:25

from django.db import migrations, models

import posts_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0004_alter_posts_cover_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="tags",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="posts",
            name="cover_path",
            field=models.ImageField(upload_to=posts_app.models.upload_cover),
        ),
    ]
