# Generated by Django 5.0.6 on 2024-05-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0005_posts_tags_alter_posts_cover_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
    ]
