# Generated by Django 5.0.6 on 2024-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0006_alter_posts_comments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
