# Generated by Django 5.0.6 on 2024-05-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts_app", "0008_alter_posts_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="comments_count",
        ),
    ]
