# Generated by Django 5.0.6 on 2024-05-08 12:29

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "avatar_path",
                    models.ImageField(
                        blank=True, null=True, upload_to=users.models.upload_to
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
