# Generated by Django 5.0.6 on 2024-05-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments_app", "0001_initial"),
        ("posts_app", "0009_remove_posts_comments_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="posts_app.posts",
            ),
        ),
    ]
